# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025 EESSI-Scout contributors
#
# EESSI-Scout automates identification of missing or outdated software packages
# in the EESSI stack, analyzes dependencies, and verifies license compatibility.
# This workflow runs linting and static analysis checks.

name: Markdown Lint & Spellcheck

on: [push, pull_request, workflow_dispatch]

# Declare default permissions as read only.
permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: '3.11'

      - name: Install EESSI-Scout (dev)
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      # define options to commands via pyproject.toml
      - name: Code formatting & lint
        run: |
          black --check --diff .
          flake8
          mypy

      - name: Markdown lint
        uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: "**/*.md"

      - name: Spell check
        uses: codespell-project/actions-codespell@8f01853be192eb0f849a5c7d721450e7a467c579 # v2.2
        with:
          check_filenames: true
          check_hidden: true
          skip: "*.png,*.jpg,*.svg,*.gif"
